---
title: "1ero de Mayo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs}
pacman::p_load(tidyverse, ggthemes, readxl, cowplot, magick, ggforce, ggtext, RColorBrewer, showtext, grid, ggqr, MetBrewer)

font_add_google(name = 'Noto Sans', "font")
showtext_auto()
```

```{r upload}
# Median weekly earnings of full-time wage and salary workers by union affiliation and selected characteristics - annual averages
union <- read_excel("C:/Users/urlo2939/Documents/GitHub/dia-del-trabajo/cpsaat41.xlsx")
# Median weekly earnings of full-time wage and salary workers by union affiliation, occupation, and industry - annual averages
union_ocup <- read_excel("C:/Users/urlo2939/Documents/GitHub/dia-del-trabajo/cpsaat43.xlsx")

png <- magick::image_read(path = "~/GitHub/dia-del-trabajo/alu_logo.jpg")

img <- grid::rasterGrob(image = png, interpolate = T)

qr <- "https://www.nlrb.gov/about-nlrb/rights-we-protect/the-law/interfering-with-employee-rights-section-7-8a1#:~:text=Section%207%20of%20the%20National,of%20collective%20bargaining%20or%20other"

qr2 <- "https://www.ueunion.org/org_steps.html"
```

```{r union_by_feat}
union <- union %>% 
  mutate(variable = paste0(characteristic, ", ", demo)) %>% 
  pivot_longer(cols = 3:6, names_to = "union", values_to = "wage")

colors <- c("#ffd28f", "#0064ab", "#005083", "#c99f6e", "#9f8a89")

vars <- c("Asian, Both", "Asian, Men", "Asian, Women", 
          "Black, Both", "Black, Men", "Black, Women",
          "Hispanic or Latino, Both", "Hispanic or Latino, Men", "Hispanic or Latino, Women",
          "White, Both", "White, Men", "White, Women",
          "Men, 16 years and over", "Women, 16 years and over", "Total, 16 years and over")

uniondiff <- union %>% 
  filter(union %in% c("Members of unions", "Non-union"),
         variable %in% vars) %>% 
  pivot_wider(names_from = union, values_from = wage) %>% 
  rename(union = 'Members of unions', non_union = 'Non-union') %>% 
  mutate(color = if_else(demo == "16 years and over", "#ffd28f", 
                         if_else(characteristic == "White", "#0064ab",
                                                if_else(characteristic == "Black", "#005083",
                                                        if_else(characteristic == "Asian", "#c99f6e",
                                                                if_else(characteristic == "Hispanic or Latino", "#9f8a89", NA_character_)))))) %>% 
  group_by(year, variable, color) %>% 
  summarise(wage_diff = union - non_union) %>% 
  ungroup() %>% 
  mutate(desc = if_else(wage_diff > 0, paste0("$", wage_diff), paste0("-$", abs(wage_diff))))
```

```{r p1, fig.height=9, fig.width=12}
uniondiff %>% 
  filter(year %in% c(2021)) %>% 
  ggplot(aes(x = wage_diff, y = reorder(variable, wage_diff))) +
  geom_vline(xintercept = 0, color = "gray40", size = 1.4) +
  geom_mark_rect(aes(label = variable, color = color, filter = str_starts(variable, c("Hispanic or Latino, ")), description = desc), 
                 label.colour = "#005083", label.fill = "transparent", label.fontsize = 10, label.buffer = unit(45, 'mm'), label.hjust = 0,
                 con.cap = 0, con.colour = "#005083", con.border = "none",
                 expand = unit(1, "mm"), radius = unit(1, "mm"), show.legend = F) +
  
  geom_mark_rect(aes(label = variable, color = color, filter = str_starts(variable, c("Total, 16 years")), description = desc), 
                 label.colour = "#9f8a89", label.fill = "transparent", label.fontsize = 10, label.buffer = unit(12, 'mm'), label.hjust = 0,
                 con.cap = 0, con.colour = "#9f8a89", con.border = "none", 
                 expand = unit(1, "mm"), radius = unit(1, "mm"), show.legend = F) +
  geom_point(aes(size = wage_diff, color = color), show.legend = F, shape = 21, fill = "white", stroke = 4.5) +
  geom_mark_rect(aes(label = variable, color = color, filter = str_starts(variable, c("Black, ")), description = desc), 
                 label.colour = "#ffd28f", label.fill = "transparent", label.fontsize = 10, 
                 con.cap = 0, con.colour = "#ffd28f", con.border = "none", 
                 expand = unit(0, "mm"), radius = unit(3, "mm"), show.legend = F) +
  scale_color_manual(values = colors) +
  scale_x_continuous(limits = c(-200, 300), breaks = seq(-200, 300, 50), labels = scales::dollar_format()) +
  draw_text(text = "On this side, workers that are members of unions\nearn on average more than non-union workers", 
            x = 210, y = 1.2, size = 11, color = "gray50", family = "font", lineheight = 1, fontface = "bold") +
  coord_cartesian(clip = "off") +
  labs(x = "Difference in median weekly earnings", 
       y = "", 
       title = NULL,
       subtitle = "Should I join a UNION? Since 2012,  the median weekly earnings of full-time wage and salary workers have been larger for Members of Unions than for Non-union workers. 2021 data shows that Hispanic or Latino workers who are members of a union earn an average of $277 more than those who are not members of a union.",
       caption = ) +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        plot.title.position = "plot", 
        plot.subtitle = element_textbox_simple(size = 12, lineheight = 1.1, 
                                            padding = margin(3, 3, 3, 3), 
                                            margin = margin(2, 0, 10, 0), 
                                            fill = "cornsilk", halign = 0, family = "font"),
        plot.margin = margin(t = 5, r = 25, b = 10, l = 25),
        axis.text = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.4, margin = margin(t = 25), size = 14),
        text = element_text(family = "font")) +
  geom_qr(aes(label = qr, x = -150, y = 11.5), size = 1.3) +
  annotate("curve", x = -110, xend = -165, y = 8.5, yend = 10.2, color = "gray60", curvature = -.45, 
           arrow = arrow(angle = 15, length = unit(3.5, "mm"), type = "closed")) +
  annotate("text", x = -85, y = 8.5, label = "more info\nscan here", color = "gray60", 
           size = 4, hjust = 0.5, vjust = 0.5, lineheight = 1, family = "font") -> p1
```

```{r emoji, fig.height=11, fig.width=12}
uniondiff %>% 
  filter(year %in% c(2021)) %>% 
  ggplot(aes(x = wage_diff, y = reorder(variable, wage_diff))) +
  geom_vline(xintercept = 0, color = "gray40", size = 1.5) +
  geom_mark_rect(aes(label = variable, color = color, filter = str_starts(variable, c("Hispanic or Latino, ")), description = desc), 
                 label.colour = "#0064ab", label.fill = "transparent", label.fontsize = 10, label.buffer = unit(40, 'mm'), 
                 con.cap = 0, con.colour = "#0064ab", con.border = "none",
                 expand = unit(3, "mm"), radius = unit(1, "mm"), show.legend = F) +
  geom_mark_rect(aes(label = variable, color = color, filter = str_starts(variable, c("Black, ")), description = desc), 
                 label.colour = "#c99f6e", label.fill = "transparent", label.fontsize = 10, label.buffer = unit(55, 'mm'),
                 con.cap = 0, con.colour = "#c99f6e", con.border = "none",
                 expand = unit(3, "mm"), radius = unit(1, "mm"), show.legend = F) +
  geom_mark_rect(aes(label = variable, color = color, filter = str_starts(variable, c("Total, 16 years")), description = desc), 
                 label.colour = "#6876a4", label.fill = "transparent", label.fontsize = 10, label.buffer = unit(5, 'mm'),
                 con.cap = 0, con.colour = "#6876a4", con.border = "none",
                 expand = unit(3, "mm"), radius = unit(1, "mm"), show.legend = F) +
  ggimage::geom_emoji(aes(image = ifelse(wage_diff > 0, '1f600', '1f622'))) +
  scale_x_continuous(limits = c(-200, 300), breaks = seq(-200, 300, 50), labels = scales::dollar_format()) +
  labs(x = "Difference in median weekly earnings", 
       y = "", 
       title = "L a b o u r   D a y",
       subtitle = "Should I join a UNION? Since 2012,  the median weekly earnings of full-time wage and salary workers have been larger for Members of Unions than for Non-union workers. 2021 data shows that Hispanic or Latino workers who are members of a union earn an average of $277 more than those who are not members of a union.",
       caption = "\n\n\n\n\nSource: US Bureau of Labor Statistics. Current Population Survey 2022.\nData refer to members of a labor union or an employee association similar to a union and to workers who are neither members of a union nor represented by a union on their job.\nPersons whose ethnicity is identified as Hispanic or Latino may be of any race. Data refer to the sole or principal job of full-time wage and salary workers.\nAll self-employed workers are excluded, both those with incorporated businesses and those with unincorporated businesses.\nUpdated population controls are introduced annually with the release of January data.") +
  annotation_custom(grob = img, 
                    ymin = 31, ymax = 40, 
                    xmin = -360, xmax = -250) +
  draw_text(text = "On this side, workers that are members of unions\nearn on average more than non-union workers", 
            x = 220, y = 3, size = 12, color = "gray40", family = "font") +
  coord_cartesian(clip = "off") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        plot.title.position = "panel", 
        plot.title = element_textbox_simple(size = 13, lineheight = 1.5, 
                                            padding = margin(3, 3, 3, 3), 
                                            margin = margin(0, 0, 0, 0), 
                                            fill = "cornsilk", halign = 0.5, 
                                            face = "bold"), 
        plot.subtitle = element_textbox_simple(size = 12, lineheight = 1, 
                                            padding = margin(3, 3, 3, 3), 
                                            margin = margin(2, 0, 10, 0), 
                                            fill = "cornsilk", halign = 0.5),
        plot.margin = margin(40, 45, 45, 45),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, color = "gray50", size = 8),
        axis.text = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.4, margin = margin(t = 25), size = 14),
        text = element_text(family = "font")) -> plot


plot + geom_qr(aes(label = qr, x = -150, y = 25), size = 1.3) +
  annotate("curve", x = -110, xend = -165, y = 17, yend = 21, color = "gray60", curvature = -.45, alpha = 0.9, 
           arrow = arrow(angle = 15, length = unit(3.5, "mm"), type = "closed")) +
  annotate("text", x = -109, y = 17, label = "more info here", color = "gray60", size = 4, hjust = 0, vjust = 0.5)

ggsave(filename = "labour_day.png", plot = last_plot(), device = "png", width = 16, height = 15, units = "in", dpi = "screen")
```

```{r union_by_ocup}
union_ocup <- union_ocup %>% 
  mutate(`Members of unions` = as.numeric(`Members of unions`), `Represented by unions` = as.numeric(`Represented by unions`)) %>% 
  pivot_longer(cols = 2:5, names_to = "union", values_to = "wage") %>% 
  filter(!is.na(union))

# colors <- c("#ffd28f", "#f0b64d", "#6876a4", "#0064ab", "#005083", "#c99f6e", "#9f8a89")
  
unionocupdiff <- union_ocup %>% 
  filter(union %in% c("Members of unions", "Non-union")) %>% 
  pivot_wider(names_from = union, values_from = wage) %>% 
  rename(union = 'Members of unions', non_union = 'Non-union') %>% 
  mutate(wage_diff = union - non_union) %>% 
  mutate(desc = if_else(wage_diff > 0, paste0("$", wage_diff), paste0("-$", abs(wage_diff))),
         unionlab = paste0("$", union),
         nonunionlab = paste0("$", non_union)) %>% 
  mutate(Occupation = if_else(Occupation != "Total full-time wage and salary workers", str_sub(Occupation, 1, nchar(Occupation)-12), Occupation)) %>% 
  filter(!is.na(wage_diff))
```

```{r p2, fig.height=9, fig.width=12}
unionocupdiff %>% 
  filter(year == 2021) %>% 
  ggplot(aes(x = union, y = reorder(Occupation, union))) +
  geom_segment(aes(xend = non_union, yend = Occupation, size = log(100*wage_diff), alpha = 0.95), color = "#cfe1eb", show.legend = F) +
  geom_segment(aes(xend = union - 7, yend = Occupation, size = log(100*wage_diff)), color = "#0064ab", show.legend = F) +
  geom_segment(aes(x = non_union, xend = non_union + 7, yend = Occupation, size = log(100*wage_diff)), color = "#c99f6e", show.legend = F) +
  geom_text(aes(x = union, y = Occupation, label = unionlab, family = 'font'), color = "gray30", nudge_x = 30, size = 3.5) +
  geom_text(aes(x = non_union, y = Occupation, label = nonunionlab, family = 'font'), color = "gray30", nudge_x = -30, size = 3.5) +
  geom_text(data = unionocupdiff %>% filter(Occupation != "Personal care and service occupations" & year == 2021),
            aes(x = union - (wage_diff/2), y = Occupation, label = desc, family = 'font'), color = "gray40", nudge_x = 0, size = 3) +
  coord_cartesian(clip = "off") +
  annotate("curve", x = 1495, xend = 1460, y = 10.1, yend = 11.9, color = "gray60", curvature = .35, 
           arrow = arrow(angle = 25, length = unit(3, "mm"), type = "closed")) +
  annotate("text", x = 1495, y = 9.7, label = "members of unions\naverage median weekly\nearnings by occupation", color = "gray60", 
           size = 3, hjust = 0.5, vjust = 0.5, lineheight = 1, family = "font") +
  annotate("curve", x = 755, xend = 930, y = 11.5, yend = 10.9, color = "gray60", curvature = .35, 
           arrow = arrow(angle = 25, length = unit(3, "mm"), type = "closed")) +
   annotate("text", x = 750, y = 11.9, label = "non-union members\naverage median weekly\nearnings by occupation", color = "gray60", 
           size = 3, hjust = 0.5, vjust = 0.5, lineheight = 1, family = "font") +
  annotate("curve", x = 1100, xend = 1210, y = 2.3, yend = 2.9, color = "gray60", curvature = -.35, 
           arrow = arrow(angle = 20, length = unit(3, "mm"), type = "closed")) +
  annotate("text", x = 1100, y = 2, label = "more info\nscan here", color = "gray60", 
           size = 4, hjust = 0.5, vjust = 0.5, lineheight = 1, family = "font") +
  geom_qr(aes(label = qr2, x = 1300, y = 2.5), size = 1.3) +
  scale_x_continuous(limits = c(500, 1500), breaks = seq(500, 1500, 200), labels = scales::dollar_format()) +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 27)) +
  labs(x = "Median weekly earnings", 
       y = "", 
       title = NULL,
       subtitle = "In 2021, the median weekly earnings of full-time wage and salary workers have been larger for Members of Unions than for Non-union workers. 2021 data shows that workers who are members of a union earn an average more than those who are not members of a union. Members of Unions on Protective service, Construction and extraction, Service, and Installation, maintenance, and repair occupations have on average higher earnings than those not affiliated with a union.") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        plot.title.position = "plot", 
        plot.subtitle = element_textbox_simple(size = 12, lineheight = 1.1, 
                                            padding = margin(3, 3, 3, 3), 
                                            margin = margin(3, 0, 10, 0), 
                                            fill = "cornsilk", halign = 0),
        plot.margin = margin(t = 10, r = 25, b = 10, l = 25),
        axis.text = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.4, margin = margin(t = 25), size = 14),
        text = element_text(family = "font")) -> p2
```

```{r top, fig.height=2, fig.width=12}
# Title and subtitle
ggdraw() +
  draw_text("L  a  b  o  u  r     D  a  y", 
            x = 0.2, y = 0.5, size = 38, family = "font", hjust = 0, colour = "red3", fontface = "bold") -> title_plot

# Top images
plot_grid(img, title_plot, ncol = 2, rel_widths = c(0.5, 2.5)) -> top_plot
```

```{r caption, fig.height=1, fig.width=12}
# Caption
ggdraw() +
  draw_text("Source: US Bureau of Labor Statistics. Current Population Survey 2022.\nData refer to members of a labor union or an employee association similar to a union and to workers who are neither members of a union nor represented by a union on their job.\nPersons whose ethnicity is identified as Hispanic or Latino may be of any race. Data refer to the sole or principal job of full-time wage and salary workers. All self-employed workers\nare excluded, both those with incorporated businesses and those with unincorporated businesses. Updated population controls are introduced annually with the release of January data.\nEffective with January 2020 data, occupations reflect the introduction of the 2018 Census occupational classification system, derived from the 2018 Standard Occupational Classification (SOC).", size = 8, x = 0.01, y = 0.5, hjust = 0, color = "gray50", family = "font") -> caption_plot

# Author
ggdraw() +
  draw_text("github.com/uriellomeli", size = 9, x = 0.95, y = 0.5, hjust = 1, color = "gray80", family = "font") +
  #draw_text("ig @iguwuana", size = 10, x = 0.95, y = 0.20, hjust = 1, color = "gray70", family = "font") +
  draw_text("ig @uriellomeli", size = 9, x = 0.95, y = 0.35, hjust = 1, color = "gray80", family = "font") -> ids_plot

# Bottom
plot_grid(caption_plot, ids_plot, ncol = 2, rel_widths = c(2.5, 0.9)) -> bottom_plot
```

```{r labour_day, fig.height=21, fig.width=12}
labour_day <- plot_grid(top_plot,
                        p1, 
                        p2,
                        bottom_plot, 
                        rel_heights = c(2, 9, 9, 1),
                        nrow = 4)
```

```{r save}
ggsave(filename = "~/GitHub/dia-del-trabajo/labour_day.png", plot = labour_day, height = 23, width = 12, units = "in", dpi = "screen")

ggsave(filename = "~/GitHub/dia-del-trabajo/labour_day.pdf", plot = labour_day, height = 23, width = 12, device = "pdf")
```






